# Generated by Django 2.2.4 on 2019-09-11 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainscrap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='csv_save',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000)),
                ('username', models.CharField(max_length=40)),
                ('csv_file', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.DeleteModel(
            name='cvs_save',
        ),
    ]
