# Generated by Django 2.2.4 on 2019-09-19 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainscrap', '0004_auto_20190912_1017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='username',
            new_name='filename',
        ),
        migrations.AddField(
            model_name='data',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
